### ISSUE TITLE
flux_article_manager_view

### ISSUE THREAD

**Issue by Stjoo0925** [Flux2024/Flux_FrontServer#18]
아티클 포스트 수정

**Comment by KHY90** [comment]
![Image](https://github.com/user-attachments/assets/2cca8d34-3228-451d-a726-f74686247ef0)

**Comment by KHY90** [comment]
이건 관리자가 아티클 세부페이지를 볼 때 나오는 페이지입니다.
수정 페이지는 추가할께요
